/**
 * Agero ERP — Default Cost Plan Content
 *
 * 24 sections (IH through ZZ) with pre-filled lines for commercial fitout.
 * Each new lead calls createDefaultCostPlan() which seeds these into the estimate.
 *
 * line_structure values: SUB_HEADING | STANDARD_LINE | NOTE_LINE
 */

export type DefaultLine = {
  line_structure: 'SUB_HEADING' | 'STANDARD_LINE' | 'NOTE_LINE';
  description: string;
  unit: string;
  default_rate: number;
  sort_order: number;
};

export type DefaultSection = {
  code: string;
  name: string;
  order: number;
  lines: DefaultLine[];
};

export const DEFAULT_COST_PLAN: DefaultSection[] = [
  {
    code: 'IH',
    name: 'Agero In-House Professional Services',
    order: 1,
    lines: [
      { line_structure: 'SUB_HEADING',    description: 'Pre Construction',        unit: '',    default_rate: 0,   sort_order: 1 },
      { line_structure: 'STANDARD_LINE',  description: 'Director',                 unit: 'LS',  default_rate: 165, sort_order: 2 },
      { line_structure: 'STANDARD_LINE',  description: 'Consultant / Design Manager', unit: 'LS', default_rate: 80, sort_order: 3 },
      { line_structure: 'STANDARD_LINE',  description: 'Proj. Co-Ordinator',       unit: 'LS',  default_rate: 70,  sort_order: 4 },
      { line_structure: 'SUB_HEADING',    description: 'Delivery',                  unit: '',    default_rate: 0,   sort_order: 5 },
      { line_structure: 'STANDARD_LINE',  description: 'Project Manager',           unit: 'LS',  default_rate: 100, sort_order: 6 },
      { line_structure: 'STANDARD_LINE',  description: 'Contract Admin',            unit: 'LS',  default_rate: 85,  sort_order: 7 },
      { line_structure: 'STANDARD_LINE',  description: 'Site Manager',              unit: 'HRS', default_rate: 106, sort_order: 8 },
      { line_structure: 'STANDARD_LINE',  description: 'Proj. Co-Ordinator',        unit: 'HRS', default_rate: 70,  sort_order: 9 },
      { line_structure: 'STANDARD_LINE',  description: 'General Labour',            unit: 'LS',  default_rate: 55,  sort_order: 10 },
    ],
  },
  {
    code: 'CO',
    name: 'Consultant Fees',
    order: 2,
    lines: [
      { line_structure: 'STANDARD_LINE', description: 'Design And Architectural',              unit: 'EA', default_rate: 0, sort_order: 1 },
      { line_structure: 'STANDARD_LINE', description: 'Services Engineer',                     unit: 'EA', default_rate: 0, sort_order: 2 },
      { line_structure: 'STANDARD_LINE', description: 'Other Engineering (Structure Etc)',     unit: 'EA', default_rate: 0, sort_order: 3 },
      { line_structure: 'STANDARD_LINE', description: 'Other Consultant - DDA',                unit: 'EA', default_rate: 0, sort_order: 4 },
      { line_structure: 'STANDARD_LINE', description: 'Other Consultant',                      unit: 'EA', default_rate: 0, sort_order: 5 },
      { line_structure: 'STANDARD_LINE', description: 'Building Surveyor Fees, Consult / Report', unit: 'EA', default_rate: 0, sort_order: 6 },
    ],
  },
  {
    code: 'PP',
    name: 'Pre-Construction Preliminaries',
    order: 3,
    lines: [
      { line_structure: 'STANDARD_LINE', description: 'Pre-Construction Allowance', unit: 'LS', default_rate: 0, sort_order: 1 },
    ],
  },
  {
    code: 'CA',
    name: 'Certification And Approvals',
    order: 4,
    lines: [
      { line_structure: 'STANDARD_LINE', description: 'Building Permit',          unit: 'LS', default_rate: 0, sort_order: 1 },
      { line_structure: 'STANDARD_LINE', description: 'Occupancy Permit',         unit: 'LS', default_rate: 0, sort_order: 2 },
      { line_structure: 'STANDARD_LINE', description: 'Authority / Council Fees', unit: 'EA', default_rate: 0, sort_order: 3 },
    ],
  },
  {
    code: 'JC',
    name: 'Overheads',
    order: 5,
    lines: [
      { line_structure: 'SUB_HEADING',   description: 'Pre-Construction',          unit: '',   default_rate: 0,    sort_order: 1 },
      { line_structure: 'STANDARD_LINE', description: 'Pre-Con Month Contribution', unit: 'EA', default_rate: 0,   sort_order: 2 },
      { line_structure: 'SUB_HEADING',   description: 'Delivery',                   unit: '',   default_rate: 0,   sort_order: 3 },
      { line_structure: 'STANDARD_LINE', description: 'Del. Monthly Contribution',  unit: 'EA', default_rate: 0,   sort_order: 4 },
      { line_structure: 'STANDARD_LINE', description: 'Project Overheads',          unit: 'EA', default_rate: 8000, sort_order: 5 },
    ],
  },
  {
    code: 'CP',
    name: 'Construction Preliminaries',
    order: 6,
    lines: [
      { line_structure: 'SUB_HEADING',   description: 'Offices + Site Accommodation', unit: '', default_rate: 0, sort_order: 1 },
      { line_structure: 'STANDARD_LINE', description: 'Site Establishment',           unit: 'EA',  default_rate: 1500, sort_order: 2 },
      { line_structure: 'STANDARD_LINE', description: 'Stores',                       unit: 'EA',  default_rate: 0,    sort_order: 3 },
      { line_structure: 'STANDARD_LINE', description: 'Washing / Ablutions',          unit: 'EA',  default_rate: 0,    sort_order: 4 },
      { line_structure: 'STANDARD_LINE', description: 'First Aid',                    unit: 'EA',  default_rate: 0,    sort_order: 5 },
      { line_structure: 'STANDARD_LINE', description: 'Establish / Dismantle',        unit: 'EA',  default_rate: 0,    sort_order: 6 },
      { line_structure: 'STANDARD_LINE', description: 'Office Furniture',             unit: 'EA',  default_rate: 0,    sort_order: 7 },
      { line_structure: 'STANDARD_LINE', description: 'Office Equipment',             unit: 'EA',  default_rate: 0,    sort_order: 8 },
      { line_structure: 'STANDARD_LINE', description: 'IT',                           unit: 'EA',  default_rate: 0,    sort_order: 9 },
      { line_structure: 'STANDARD_LINE', description: 'Maintenance',                  unit: 'EA',  default_rate: 0,    sort_order: 10 },
      { line_structure: 'STANDARD_LINE', description: 'Consumables',                  unit: 'EA',  default_rate: 0,    sort_order: 11 },
      { line_structure: 'STANDARD_LINE', description: 'Stationery',                   unit: 'EA',  default_rate: 0,    sort_order: 12 },
      { line_structure: 'STANDARD_LINE', description: 'Plan Copying',                 unit: 'EA',  default_rate: 0,    sort_order: 13 },
      { line_structure: 'STANDARD_LINE', description: 'Photocopying',                 unit: 'EA',  default_rate: 0,    sort_order: 14 },
      { line_structure: 'STANDARD_LINE', description: 'Photographs',                  unit: 'EA',  default_rate: 0,    sort_order: 15 },
      { line_structure: 'STANDARD_LINE', description: 'Petty Cash',                   unit: 'EA',  default_rate: 0,    sort_order: 16 },
      { line_structure: 'STANDARD_LINE', description: 'Cleaning',                     unit: 'EA',  default_rate: 0,    sort_order: 17 },
      { line_structure: 'STANDARD_LINE', description: 'Cleaning Equipment',           unit: 'EA',  default_rate: 0,    sort_order: 18 },
      { line_structure: 'STANDARD_LINE', description: 'Signage',                      unit: 'EA',  default_rate: 0,    sort_order: 19 },
      { line_structure: 'STANDARD_LINE', description: 'Temporary Power',              unit: 'EA',  default_rate: 0,    sort_order: 20 },
      { line_structure: 'STANDARD_LINE', description: 'Temporary Lighting',           unit: 'EA',  default_rate: 0,    sort_order: 21 },
      { line_structure: 'STANDARD_LINE', description: 'Goods Lift Attendant',         unit: 'EA',  default_rate: 0,    sort_order: 22 },
      { line_structure: 'STANDARD_LINE', description: 'Protect And Make Good Goods Lift', unit: 'EA', default_rate: 0, sort_order: 23 },
      { line_structure: 'STANDARD_LINE', description: 'Telephone System',             unit: 'EA',  default_rate: 0,    sort_order: 24 },
      { line_structure: 'STANDARD_LINE', description: 'Telephone Accounts',           unit: 'EA',  default_rate: 0,    sort_order: 25 },
      { line_structure: 'STANDARD_LINE', description: 'Mobile Phone Charges',         unit: 'EA',  default_rate: 0,    sort_order: 26 },
      { line_structure: 'STANDARD_LINE', description: 'Water Connection',             unit: 'EA',  default_rate: 0,    sort_order: 27 },
      { line_structure: 'STANDARD_LINE', description: 'Water Supply',                 unit: 'EA',  default_rate: 0,    sort_order: 28 },
      { line_structure: 'STANDARD_LINE', description: 'Small Tools',                  unit: 'EA',  default_rate: 0,    sort_order: 29 },
      { line_structure: 'STANDARD_LINE', description: 'Cartage And Couriers',         unit: 'EA',  default_rate: 0,    sort_order: 30 },
      { line_structure: 'STANDARD_LINE', description: 'Temporary Fire Services',      unit: 'EA',  default_rate: 0,    sort_order: 31 },
      { line_structure: 'STANDARD_LINE', description: 'Fire Extinguisher',            unit: 'EA',  default_rate: 0,    sort_order: 32 },
      { line_structure: 'STANDARD_LINE', description: 'Protection',                   unit: 'EA',  default_rate: 0,    sort_order: 33 },
      { line_structure: 'STANDARD_LINE', description: 'Locksmith',                    unit: 'EA',  default_rate: 0,    sort_order: 34 },
      { line_structure: 'STANDARD_LINE', description: 'Security',                     unit: 'EA',  default_rate: 0,    sort_order: 35 },
      { line_structure: 'SUB_HEADING',   description: 'Survey (Land / Area)',         unit: '',    default_rate: 0,    sort_order: 36 },
      { line_structure: 'STANDARD_LINE', description: 'Dilapidation Report',          unit: 'EA',  default_rate: 0,    sort_order: 37 },
      { line_structure: 'STANDARD_LINE', description: 'Setting Out',                  unit: 'EA',  default_rate: 0,    sort_order: 38 },
      { line_structure: 'STANDARD_LINE', description: 'Surveyor Fees',                unit: 'EA',  default_rate: 0,    sort_order: 39 },
      { line_structure: 'SUB_HEADING',   description: 'Permits',                      unit: '',    default_rate: 0,    sort_order: 40 },
      { line_structure: 'STANDARD_LINE', description: 'Div 6 - Greencap',             unit: 'EA',  default_rate: 0,    sort_order: 41 },
      { line_structure: 'STANDARD_LINE', description: 'Asset Protection',             unit: 'EA',  default_rate: 0,    sort_order: 42 },
      { line_structure: 'STANDARD_LINE', description: 'Building Permit Levy Fee',     unit: 'EA',  default_rate: 0,    sort_order: 43 },
      { line_structure: 'SUB_HEADING',   description: 'Safety',                       unit: '',    default_rate: 0,    sort_order: 44 },
      { line_structure: 'STANDARD_LINE', description: 'Safety Equipment',             unit: 'EA',  default_rate: 0,    sort_order: 45 },
      { line_structure: 'STANDARD_LINE', description: 'Inductions',                   unit: 'EA',  default_rate: 0,    sort_order: 46 },
      { line_structure: 'STANDARD_LINE', description: 'First Aid Supplies',           unit: 'EA',  default_rate: 0,    sort_order: 47 },
      { line_structure: 'SUB_HEADING',   description: 'Fees, Insurances + Disbursements', unit: '', default_rate: 0,  sort_order: 48 },
      { line_structure: 'STANDARD_LINE', description: 'Authority / Council Fees',     unit: 'EA',  default_rate: 0,    sort_order: 49 },
      { line_structure: 'STANDARD_LINE', description: 'Insurance / Upgrades',         unit: 'EA',  default_rate: 0,    sort_order: 50 },
      { line_structure: 'STANDARD_LINE', description: 'Excess',                       unit: 'EA',  default_rate: 0,    sort_order: 51 },
      { line_structure: 'STANDARD_LINE', description: 'Bank Guarantee',               unit: 'EA',  default_rate: 0,    sort_order: 52 },
      { line_structure: 'STANDARD_LINE', description: 'Car Parking',                  unit: 'MTH', default_rate: 450,  sort_order: 53 },
      { line_structure: 'STANDARD_LINE', description: 'Transport And Accommodation',  unit: 'EA',  default_rate: 0,    sort_order: 54 },
      { line_structure: 'STANDARD_LINE', description: 'Living Away From Home',        unit: 'EA',  default_rate: 0,    sort_order: 55 },
      { line_structure: 'STANDARD_LINE', description: 'Loading Fees',                 unit: 'EA',  default_rate: 0,    sort_order: 56 },
      { line_structure: 'SUB_HEADING',   description: 'Temporary + Protection Works', unit: '',    default_rate: 0,    sort_order: 57 },
      { line_structure: 'STANDARD_LINE', description: 'Floor Protection',             unit: 'M2',  default_rate: 5,    sort_order: 58 },
      { line_structure: 'STANDARD_LINE', description: 'Other Protection Works - Lift, Lobby, Toilets and Amenities', unit: 'EA', default_rate: 3000, sort_order: 59 },
      { line_structure: 'STANDARD_LINE', description: 'Access 1: Scissor Lift',       unit: 'WKS', default_rate: 550,  sort_order: 60 },
      { line_structure: 'STANDARD_LINE', description: 'Access 2',                     unit: 'EA',  default_rate: 0,    sort_order: 61 },
      { line_structure: 'STANDARD_LINE', description: 'Hoardings',                    unit: 'WKS', default_rate: 0,    sort_order: 62 },
      { line_structure: 'STANDARD_LINE', description: 'Temporary Works - Relocate Workstations', unit: 'EA', default_rate: 150, sort_order: 63 },
      { line_structure: 'STANDARD_LINE', description: 'Making Good',                  unit: 'EA',  default_rate: 0,    sort_order: 64 },
      { line_structure: 'SUB_HEADING',   description: 'Close Out',                    unit: '',    default_rate: 0,    sort_order: 65 },
      { line_structure: 'STANDARD_LINE', description: 'Attend To Defects',            unit: 'EA',  default_rate: 0,    sort_order: 66 },
      { line_structure: 'STANDARD_LINE', description: 'Operation Manuals, Warranties And AS Built Dwgs', unit: 'EA', default_rate: 0, sort_order: 67 },
      { line_structure: 'STANDARD_LINE', description: 'Final Clean',                  unit: 'M2',  default_rate: 8,    sort_order: 68 },
      { line_structure: 'STANDARD_LINE', description: 'Skips',                        unit: 'EA',  default_rate: 900,  sort_order: 69 },
    ],
  },
  {
    code: 'DE',
    name: 'Demolition',
    order: 7,
    lines: [
      { line_structure: 'SUB_HEADING',   description: 'Scope of Work',               unit: '',    default_rate: 0,  sort_order: 1 },
      { line_structure: 'STANDARD_LINE', description: 'Plasterboard Ceiling',         unit: 'M2',  default_rate: 30, sort_order: 2 },
      { line_structure: 'STANDARD_LINE', description: 'Ceiling Grid & Tile',          unit: 'M2',  default_rate: 20, sort_order: 3 },
      { line_structure: 'STANDARD_LINE', description: 'Walls - Plasterboard / Glazing', unit: 'M2', default_rate: 40, sort_order: 4 },
      { line_structure: 'STANDARD_LINE', description: 'Allowance To Remove Existing Loose Furniture And Joinery', unit: 'EA', default_rate: 150, sort_order: 5 },
      { line_structure: 'STANDARD_LINE', description: 'Carpet Removal',               unit: 'M2',  default_rate: 20, sort_order: 6 },
      { line_structure: 'STANDARD_LINE', description: 'Removal of Glue',              unit: 'M2',  default_rate: 8,  sort_order: 7 },
      { line_structure: 'STANDARD_LINE', description: 'Vinyl',                        unit: 'M2',  default_rate: 50, sort_order: 8 },
      { line_structure: 'STANDARD_LINE', description: 'Tiles',                        unit: 'M2',  default_rate: 50, sort_order: 9 },
      { line_structure: 'STANDARD_LINE', description: 'Screed Removal',               unit: 'M2',  default_rate: 20, sort_order: 10 },
      { line_structure: 'STANDARD_LINE', description: 'Wall Vinyl Graphics Removal',  unit: 'LM',  default_rate: 30, sort_order: 11 },
      { line_structure: 'STANDARD_LINE', description: 'Selective Demolition Detail',  unit: 'LS',  default_rate: 0,  sort_order: 12 },
      { line_structure: 'SUB_HEADING',   description: 'Design Development / Pre Construction', unit: '', default_rate: 0, sort_order: 13 },
      { line_structure: 'STANDARD_LINE', description: 'PPR / Brief Preparation',      unit: 'LS',  default_rate: 0,  sort_order: 14 },
      { line_structure: 'STANDARD_LINE', description: 'Permit Applications / Traffic Management Plan', unit: 'LS', default_rate: 0, sort_order: 15 },
      { line_structure: 'STANDARD_LINE', description: 'Resource Recovery Plan',       unit: 'LS',  default_rate: 0,  sort_order: 16 },
      { line_structure: 'STANDARD_LINE', description: 'Safety Management Plan / SWMS', unit: 'LS', default_rate: 0, sort_order: 17 },
      { line_structure: 'STANDARD_LINE', description: 'Environmental Mgmt Plan',      unit: 'LS',  default_rate: 0,  sort_order: 18 },
      { line_structure: 'SUB_HEADING',   description: 'Preliminaries + Consultants',  unit: '',    default_rate: 0,  sort_order: 19 },
      { line_structure: 'STANDARD_LINE', description: 'OHS Provisions (Dust, Silica, Hazardous Material)', unit: 'LS', default_rate: 0, sort_order: 20 },
      { line_structure: 'STANDARD_LINE', description: 'PPE',                          unit: 'LS',  default_rate: 0,  sort_order: 21 },
      { line_structure: 'STANDARD_LINE', description: 'Hygienist Cost',               unit: 'LS',  default_rate: 0,  sort_order: 22 },
      { line_structure: 'STANDARD_LINE', description: 'Protection + Hoardings',       unit: 'LS',  default_rate: 0,  sort_order: 23 },
      { line_structure: 'STANDARD_LINE', description: 'Bins',                         unit: 'EA',  default_rate: 60, sort_order: 24 },
      { line_structure: 'SUB_HEADING',   description: 'Supervision',                  unit: '',    default_rate: 0,  sort_order: 25 },
      { line_structure: 'STANDARD_LINE', description: 'Onsite Supervisor',            unit: 'LS',  default_rate: 0,  sort_order: 26 },
      { line_structure: 'STANDARD_LINE', description: 'Meeting Attendance',           unit: 'LS',  default_rate: 0,  sort_order: 27 },
      { line_structure: 'STANDARD_LINE', description: 'Works in Connection',          unit: 'LS',  default_rate: 0,  sort_order: 28 },
      { line_structure: 'STANDARD_LINE', description: 'In Connection To Structural',  unit: 'LS',  default_rate: 0,  sort_order: 29 },
      { line_structure: 'STANDARD_LINE', description: 'In Connection To Asbestos + Hazmat', unit: 'LS', default_rate: 0, sort_order: 30 },
      { line_structure: 'STANDARD_LINE', description: 'Trade Co-Ordination',          unit: 'LS',  default_rate: 0,  sort_order: 31 },
      { line_structure: 'STANDARD_LINE', description: 'Waste Management',             unit: 'LS',  default_rate: 0,  sort_order: 32 },
      { line_structure: 'SUB_HEADING',   description: 'As Built Documentation',       unit: '',    default_rate: 0,  sort_order: 33 },
      { line_structure: 'STANDARD_LINE', description: 'Demolition Process Records - Photos, ITP', unit: 'LS', default_rate: 0, sort_order: 34 },
      { line_structure: 'STANDARD_LINE', description: 'Disposal Certification',       unit: 'LS',  default_rate: 0,  sort_order: 35 },
      { line_structure: 'STANDARD_LINE', description: 'Regulatory Compliance Stat Dec', unit: 'LS', default_rate: 0, sort_order: 36 },
    ],
  },
  {
    code: 'PA',
    name: 'Partitioning, Ceilings & Doors',
    order: 8,
    lines: [
      { line_structure: 'SUB_HEADING',   description: 'Scope of Work',               unit: '',    default_rate: 0,    sort_order: 1 },
      { line_structure: 'SUB_HEADING',   description: 'Carpentry',                   unit: '',    default_rate: 0,    sort_order: 2 },
      { line_structure: 'STANDARD_LINE', description: 'Trims And Mouldings',         unit: 'LS',  default_rate: 0,    sort_order: 3 },
      { line_structure: 'STANDARD_LINE', description: 'Reuse And Door Hanging',      unit: 'LS',  default_rate: 0,    sort_order: 4 },
      { line_structure: 'SUB_HEADING',   description: 'Doors',                       unit: '',    default_rate: 0,    sort_order: 5 },
      { line_structure: 'STANDARD_LINE', description: 'New Door Type A - Semi Solid Core Door, Aluminium Frame', unit: 'EA', default_rate: 1650, sort_order: 6 },
      { line_structure: 'STANDARD_LINE', description: 'New Door Type B - Semi Solid Sliding Door With Head Track', unit: 'EA', default_rate: 1950, sort_order: 7 },
      { line_structure: 'STANDARD_LINE', description: 'New Door Type C - Aluminium Frame Glass Door', unit: 'EA', default_rate: 1950, sort_order: 8 },
      { line_structure: 'STANDARD_LINE', description: 'New Door Type D - Automatic Glass Sliding Door', unit: 'EA', default_rate: 2500, sort_order: 9 },
      { line_structure: 'STANDARD_LINE', description: 'Door Hardware',               unit: 'EA',  default_rate: 0,    sort_order: 10 },
      { line_structure: 'STANDARD_LINE', description: 'Sliding Mech',                unit: 'EA',  default_rate: 2000, sort_order: 11 },
      { line_structure: 'STANDARD_LINE', description: 'Mortice Locks',               unit: 'EA',  default_rate: 300,  sort_order: 12 },
      { line_structure: 'STANDARD_LINE', description: 'Closers',                     unit: 'EA',  default_rate: 450,  sort_order: 13 },
      { line_structure: 'STANDARD_LINE', description: 'Door Frame Type 1 - Metal / Timber / Fire rated', unit: 'EA', default_rate: 0, sort_order: 14 },
      { line_structure: 'STANDARD_LINE', description: 'Door Frame Type 2 - Acoustic (Raven Seal)', unit: 'EA', default_rate: 0, sort_order: 15 },
      { line_structure: 'STANDARD_LINE', description: 'Stairs / Handrail',           unit: 'EA',  default_rate: 0,    sort_order: 16 },
      { line_structure: 'STANDARD_LINE', description: 'New / Modify Structural Elements', unit: 'EA', default_rate: 0, sort_order: 17 },
      { line_structure: 'STANDARD_LINE', description: 'Steel',                       unit: 'EA',  default_rate: 0,    sort_order: 18 },
      { line_structure: 'STANDARD_LINE', description: 'Feature Panels / External Panels', unit: 'EA', default_rate: 0, sort_order: 19 },
      { line_structure: 'SUB_HEADING',   description: 'Ceiling',                     unit: '',    default_rate: 0,    sort_order: 20 },
      { line_structure: 'STANDARD_LINE', description: 'Ceiling Type 1 - STD Tile and Grid 600x1200', unit: 'M2', default_rate: 80, sort_order: 21 },
      { line_structure: 'STANDARD_LINE', description: 'Ceiling Type 2 - Plasterboard Ceiling', unit: 'M2', default_rate: 110, sort_order: 22 },
      { line_structure: 'STANDARD_LINE', description: 'Perforated Plasterboard Ceiling', unit: 'M2', default_rate: 250, sort_order: 23 },
      { line_structure: 'STANDARD_LINE', description: 'Ceilings - Framework Installation Only', unit: 'LS', default_rate: 0, sort_order: 24 },
      { line_structure: 'STANDARD_LINE', description: 'Ceiling Flush - Bulkheads / Vertical', unit: 'LM', default_rate: 90, sort_order: 25 },
      { line_structure: 'STANDARD_LINE', description: 'Ceiling Flush - Margin',      unit: 'LM',  default_rate: 60,   sort_order: 26 },
      { line_structure: 'STANDARD_LINE', description: 'Extra Box Ceiling Tiles',     unit: 'LS',  default_rate: 0,    sort_order: 27 },
      { line_structure: 'STANDARD_LINE', description: 'Ceiling Hatches',             unit: 'EA',  default_rate: 400,  sort_order: 28 },
      { line_structure: 'STANDARD_LINE', description: 'Acoustic Ceiling Systems',    unit: 'LS',  default_rate: 0,    sort_order: 29 },
      { line_structure: 'SUB_HEADING',   description: 'Partitions',                  unit: '',    default_rate: 0,    sort_order: 30 },
      { line_structure: 'STANDARD_LINE', description: 'Partition Type A - 64mm Stud, 13mm Plasterboard Both Sides, Insulation, Full Height', unit: 'M2', default_rate: 120, sort_order: 31 },
      { line_structure: 'STANDARD_LINE', description: 'Partition Type A - 64mm Stud, 13mm Plasterboard Both Sides, Height To 1.5m', unit: 'M2', default_rate: 125, sort_order: 32 },
      { line_structure: 'STANDARD_LINE', description: 'Partition Type C - Fire Rated Construction', unit: 'M2', default_rate: 0, sort_order: 33 },
      { line_structure: 'STANDARD_LINE', description: 'Partition Type C - Other Type Wall', unit: 'M2', default_rate: 0, sort_order: 34 },
      { line_structure: 'STANDARD_LINE', description: 'Partition Curve Wall',        unit: 'LM',  default_rate: 400,  sort_order: 35 },
      { line_structure: 'STANDARD_LINE', description: 'Powdercoating',               unit: 'LS',  default_rate: 0,    sort_order: 36 },
      { line_structure: 'STANDARD_LINE', description: 'Insulation',                  unit: 'LS',  default_rate: 0,    sort_order: 37 },
      { line_structure: 'STANDARD_LINE', description: 'Baffle Block Above The Wall - Each Layer', unit: 'LM', default_rate: 80, sort_order: 38 },
      { line_structure: 'STANDARD_LINE', description: 'Partition Type Glass A - Floor To Ceiling Glass, Powder Coated Aluminium Frames', unit: 'M2', default_rate: 365, sort_order: 39 },
      { line_structure: 'STANDARD_LINE', description: 'Partition Type Glass B - Install Only', unit: 'M2', default_rate: 0, sort_order: 40 },
      { line_structure: 'STANDARD_LINE', description: 'Partition Type Glass C - Side Light', unit: 'LS', default_rate: 0, sort_order: 41 },
      { line_structure: 'STANDARD_LINE', description: 'Glass Supply And Install',    unit: 'LS',  default_rate: 0,    sort_order: 42 },
    ],
  },
  {
    code: 'PT',
    name: 'Painting & Decorating',
    order: 9,
    lines: [
      { line_structure: 'SUB_HEADING',   description: 'Walls & Ceilings',            unit: '',    default_rate: 0,   sort_order: 1 },
      { line_structure: 'STANDARD_LINE', description: 'Wall Paint - 2 Coat System',  unit: 'M2',  default_rate: 22,  sort_order: 2 },
      { line_structure: 'STANDARD_LINE', description: 'Ceiling Paint',               unit: 'M2',  default_rate: 18,  sort_order: 3 },
      { line_structure: 'STANDARD_LINE', description: 'Feature Wall / Accent Colour', unit: 'M2', default_rate: 30,  sort_order: 4 },
      { line_structure: 'STANDARD_LINE', description: 'Skim Coat / Repair Prior To Paint', unit: 'M2', default_rate: 15, sort_order: 5 },
      { line_structure: 'SUB_HEADING',   description: 'Doors & Frames',              unit: '',    default_rate: 0,   sort_order: 6 },
      { line_structure: 'STANDARD_LINE', description: 'Paint Door And Frame',        unit: 'EA',  default_rate: 250, sort_order: 7 },
      { line_structure: 'STANDARD_LINE', description: 'Paint Skirting / Trims',      unit: 'LM',  default_rate: 8,   sort_order: 8 },
      { line_structure: 'SUB_HEADING',   description: 'Specialty',                   unit: '',    default_rate: 0,   sort_order: 9 },
      { line_structure: 'STANDARD_LINE', description: 'Epoxy Floor Coating',         unit: 'M2',  default_rate: 85,  sort_order: 10 },
      { line_structure: 'STANDARD_LINE', description: 'Line Marking',                unit: 'LS',  default_rate: 0,   sort_order: 11 },
      { line_structure: 'STANDARD_LINE', description: 'Allowance For Touch Ups',     unit: 'LS',  default_rate: 500, sort_order: 12 },
    ],
  },
  {
    code: 'FL',
    name: 'Flooring',
    order: 10,
    lines: [
      { line_structure: 'SUB_HEADING',   description: 'Carpet',                      unit: '',    default_rate: 0,    sort_order: 1 },
      { line_structure: 'STANDARD_LINE', description: 'Carpet - Supply & Install',   unit: 'M2',  default_rate: 85,   sort_order: 2 },
      { line_structure: 'STANDARD_LINE', description: 'Carpet Tile - Supply & Install', unit: 'M2', default_rate: 75, sort_order: 3 },
      { line_structure: 'SUB_HEADING',   description: 'Timber & Resilient',          unit: '',    default_rate: 0,    sort_order: 4 },
      { line_structure: 'STANDARD_LINE', description: 'Timber Floor - Supply & Install', unit: 'M2', default_rate: 180, sort_order: 5 },
      { line_structure: 'STANDARD_LINE', description: 'Vinyl Plank - Supply & Install', unit: 'M2', default_rate: 95, sort_order: 6 },
      { line_structure: 'STANDARD_LINE', description: 'Sheet Vinyl - Supply & Install', unit: 'M2', default_rate: 65, sort_order: 7 },
      { line_structure: 'SUB_HEADING',   description: 'Tiles & Stone',               unit: '',    default_rate: 0,    sort_order: 8 },
      { line_structure: 'STANDARD_LINE', description: 'Floor Tile - Supply & Install', unit: 'M2', default_rate: 120, sort_order: 9 },
      { line_structure: 'STANDARD_LINE', description: 'Stone / Porcelain Tile',      unit: 'M2',  default_rate: 180,  sort_order: 10 },
      { line_structure: 'STANDARD_LINE', description: 'Screed / Levelling Compound', unit: 'M2',  default_rate: 35,   sort_order: 11 },
      { line_structure: 'STANDARD_LINE', description: 'Transition / Edge Trims',     unit: 'LM',  default_rate: 25,   sort_order: 12 },
    ],
  },
  {
    code: 'ED',
    name: 'Electrical & Data',
    order: 11,
    lines: [
      { line_structure: 'SUB_HEADING',   description: 'General Electrical',          unit: '',    default_rate: 0,  sort_order: 1 },
      { line_structure: 'STANDARD_LINE', description: 'Electrical Fitout - Tenancy Allowance', unit: 'LS', default_rate: 0, sort_order: 2 },
      { line_structure: 'STANDARD_LINE', description: 'Switchboard / DB Modifications', unit: 'LS', default_rate: 0, sort_order: 3 },
      { line_structure: 'STANDARD_LINE', description: 'General Power Points (GPO)',  unit: 'EA',  default_rate: 185, sort_order: 4 },
      { line_structure: 'STANDARD_LINE', description: 'Lighting - Linear / Recessed', unit: 'EA', default_rate: 220, sort_order: 5 },
      { line_structure: 'STANDARD_LINE', description: 'Emergency / Exit Lighting',   unit: 'EA',  default_rate: 350, sort_order: 6 },
      { line_structure: 'SUB_HEADING',   description: 'Data & Communications',       unit: '',    default_rate: 0,   sort_order: 7 },
      { line_structure: 'STANDARD_LINE', description: 'Data Cabling - Cat6',         unit: 'EA',  default_rate: 280, sort_order: 8 },
      { line_structure: 'STANDARD_LINE', description: 'Patch Panel / Comms Cabinet', unit: 'EA',  default_rate: 1500, sort_order: 9 },
      { line_structure: 'STANDARD_LINE', description: 'Wireless Access Points (WAP)', unit: 'EA', default_rate: 850, sort_order: 10 },
      { line_structure: 'STANDARD_LINE', description: 'PA / Intercom System',        unit: 'LS',  default_rate: 0,   sort_order: 11 },
      { line_structure: 'SUB_HEADING',   description: 'Testing & Commissioning',     unit: '',    default_rate: 0,   sort_order: 12 },
      { line_structure: 'STANDARD_LINE', description: 'Testing, Commissioning & Certification', unit: 'LS', default_rate: 0, sort_order: 13 },
    ],
  },
  {
    code: 'PH',
    name: 'Plumbing & Hydraulics',
    order: 12,
    lines: [
      { line_structure: 'SUB_HEADING',   description: 'Amenities',                   unit: '',    default_rate: 0,    sort_order: 1 },
      { line_structure: 'STANDARD_LINE', description: 'Hydraulics Package - Amenities', unit: 'LS', default_rate: 0, sort_order: 2 },
      { line_structure: 'STANDARD_LINE', description: 'Sink / Basin Supply & Install', unit: 'EA', default_rate: 650, sort_order: 3 },
      { line_structure: 'STANDARD_LINE', description: 'Toilet Suite Supply & Install', unit: 'EA', default_rate: 1200, sort_order: 4 },
      { line_structure: 'STANDARD_LINE', description: 'Hot Water Unit',               unit: 'EA',  default_rate: 1500, sort_order: 5 },
      { line_structure: 'SUB_HEADING',   description: 'Kitchen / Breakout',           unit: '',    default_rate: 0,    sort_order: 6 },
      { line_structure: 'STANDARD_LINE', description: 'Kitchen Sink & Tapware',       unit: 'EA',  default_rate: 850,  sort_order: 7 },
      { line_structure: 'STANDARD_LINE', description: 'Dishwasher Connection',        unit: 'EA',  default_rate: 400,  sort_order: 8 },
      { line_structure: 'STANDARD_LINE', description: 'Waste / Drainage Works',       unit: 'LS',  default_rate: 0,    sort_order: 9 },
      { line_structure: 'STANDARD_LINE', description: 'Testing & Commissioning',      unit: 'LS',  default_rate: 0,    sort_order: 10 },
    ],
  },
  {
    code: 'ME',
    name: 'Mechanical',
    order: 13,
    lines: [
      { line_structure: 'SUB_HEADING',   description: 'Air Conditioning',            unit: '',    default_rate: 0,    sort_order: 1 },
      { line_structure: 'STANDARD_LINE', description: 'HVAC Supply & Install - Full Fitout', unit: 'LS', default_rate: 0, sort_order: 2 },
      { line_structure: 'STANDARD_LINE', description: 'VAV / FCU Modifications',     unit: 'EA',  default_rate: 1800, sort_order: 3 },
      { line_structure: 'STANDARD_LINE', description: 'Diffusers / Grilles',         unit: 'EA',  default_rate: 350,  sort_order: 4 },
      { line_structure: 'STANDARD_LINE', description: 'Ductwork Modifications',      unit: 'LS',  default_rate: 0,    sort_order: 5 },
      { line_structure: 'SUB_HEADING',   description: 'BMS & Controls',              unit: '',    default_rate: 0,    sort_order: 6 },
      { line_structure: 'STANDARD_LINE', description: 'BMS Integration & Controls',  unit: 'LS',  default_rate: 0,    sort_order: 7 },
      { line_structure: 'SUB_HEADING',   description: 'Ventilation',                 unit: '',    default_rate: 0,    sort_order: 8 },
      { line_structure: 'STANDARD_LINE', description: 'Exhaust Fan Supply & Install', unit: 'EA', default_rate: 650,  sort_order: 9 },
      { line_structure: 'STANDARD_LINE', description: 'Testing, Balancing & Commissioning', unit: 'LS', default_rate: 0, sort_order: 10 },
    ],
  },
  {
    code: 'FI',
    name: 'Fire Services',
    order: 14,
    lines: [
      { line_structure: 'SUB_HEADING',   description: 'Sprinkler System',            unit: '',    default_rate: 0,    sort_order: 1 },
      { line_structure: 'STANDARD_LINE', description: 'Sprinkler Extension & Modifications', unit: 'LS', default_rate: 0, sort_order: 2 },
      { line_structure: 'STANDARD_LINE', description: 'Sprinkler Head Relocation',   unit: 'EA',  default_rate: 450,  sort_order: 3 },
      { line_structure: 'SUB_HEADING',   description: 'Detection & Alarm',           unit: '',    default_rate: 0,    sort_order: 4 },
      { line_structure: 'STANDARD_LINE', description: 'Smoke Detector Relocation',   unit: 'EA',  default_rate: 350,  sort_order: 5 },
      { line_structure: 'STANDARD_LINE', description: 'Fire Indicator Panel (FIP) Works', unit: 'LS', default_rate: 0, sort_order: 6 },
      { line_structure: 'STANDARD_LINE', description: 'Stairwell Pressurisation',    unit: 'LS',  default_rate: 0,    sort_order: 7 },
      { line_structure: 'STANDARD_LINE', description: 'Testing & Commissioning',     unit: 'LS',  default_rate: 0,    sort_order: 8 },
    ],
  },
  {
    code: 'SE',
    name: 'Security',
    order: 15,
    lines: [
      { line_structure: 'SUB_HEADING',   description: 'Access Control',              unit: '',    default_rate: 0,    sort_order: 1 },
      { line_structure: 'STANDARD_LINE', description: 'Access Control System',       unit: 'LS',  default_rate: 0,    sort_order: 2 },
      { line_structure: 'STANDARD_LINE', description: 'Card Reader / Swipe',         unit: 'EA',  default_rate: 1200, sort_order: 3 },
      { line_structure: 'STANDARD_LINE', description: 'Door Lock / Maglock',         unit: 'EA',  default_rate: 850,  sort_order: 4 },
      { line_structure: 'SUB_HEADING',   description: 'CCTV',                        unit: '',    default_rate: 0,    sort_order: 5 },
      { line_structure: 'STANDARD_LINE', description: 'CCTV Camera Supply & Install', unit: 'EA', default_rate: 950,  sort_order: 6 },
      { line_structure: 'STANDARD_LINE', description: 'NVR / DVR Recording System',  unit: 'EA',  default_rate: 1500, sort_order: 7 },
      { line_structure: 'STANDARD_LINE', description: 'Testing & Commissioning',     unit: 'LS',  default_rate: 0,    sort_order: 8 },
    ],
  },
  {
    code: 'AV',
    name: 'Audio Visual',
    order: 16,
    lines: [
      { line_structure: 'SUB_HEADING',   description: 'Meeting Rooms',               unit: '',    default_rate: 0,    sort_order: 1 },
      { line_structure: 'STANDARD_LINE', description: 'AV Package - Small Meeting Room', unit: 'EA', default_rate: 8500, sort_order: 2 },
      { line_structure: 'STANDARD_LINE', description: 'AV Package - Large Meeting Room / Board Room', unit: 'EA', default_rate: 18000, sort_order: 3 },
      { line_structure: 'STANDARD_LINE', description: 'Display Screen / TV',         unit: 'EA',  default_rate: 2500, sort_order: 4 },
      { line_structure: 'STANDARD_LINE', description: 'Video Conferencing System',   unit: 'EA',  default_rate: 6500, sort_order: 5 },
      { line_structure: 'SUB_HEADING',   description: 'General',                     unit: '',    default_rate: 0,    sort_order: 6 },
      { line_structure: 'STANDARD_LINE', description: 'Speakers / PA System',        unit: 'LS',  default_rate: 0,    sort_order: 7 },
      { line_structure: 'STANDARD_LINE', description: 'AV Cabling & Rack',           unit: 'LS',  default_rate: 0,    sort_order: 8 },
      { line_structure: 'STANDARD_LINE', description: 'Programming & Commissioning', unit: 'LS',  default_rate: 0,    sort_order: 9 },
    ],
  },
  {
    code: 'JO',
    name: 'Joinery',
    order: 17,
    lines: [
      { line_structure: 'SUB_HEADING',   description: 'Kitchen / Breakout',          unit: '',    default_rate: 0,    sort_order: 1 },
      { line_structure: 'STANDARD_LINE', description: 'Kitchen Joinery - Supply & Install', unit: 'LM', default_rate: 1800, sort_order: 2 },
      { line_structure: 'STANDARD_LINE', description: 'Stone / Laminate Benchtop',   unit: 'LM',  default_rate: 650,  sort_order: 3 },
      { line_structure: 'SUB_HEADING',   description: 'Reception / Feature',         unit: '',    default_rate: 0,    sort_order: 4 },
      { line_structure: 'STANDARD_LINE', description: 'Reception Counter',           unit: 'EA',  default_rate: 8500, sort_order: 5 },
      { line_structure: 'STANDARD_LINE', description: 'Feature Joinery / Millwork',  unit: 'LS',  default_rate: 0,    sort_order: 6 },
      { line_structure: 'SUB_HEADING',   description: 'Storage & Workstations',      unit: '',    default_rate: 0,    sort_order: 7 },
      { line_structure: 'STANDARD_LINE', description: 'Overhead Lockers',            unit: 'LM',  default_rate: 850,  sort_order: 8 },
      { line_structure: 'STANDARD_LINE', description: 'Under Desk Pedestals',        unit: 'EA',  default_rate: 600,  sort_order: 9 },
      { line_structure: 'STANDARD_LINE', description: 'Shelving Units',              unit: 'EA',  default_rate: 450,  sort_order: 10 },
    ],
  },
  {
    code: 'FU',
    name: 'Furniture',
    order: 18,
    lines: [
      { line_structure: 'SUB_HEADING',   description: 'Workstations',               unit: '',    default_rate: 0,    sort_order: 1 },
      { line_structure: 'STANDARD_LINE', description: 'Workstation - 1200mm Bench', unit: 'EA',  default_rate: 1800, sort_order: 2 },
      { line_structure: 'STANDARD_LINE', description: 'Workstation - 1500mm Bench', unit: 'EA',  default_rate: 2200, sort_order: 3 },
      { line_structure: 'STANDARD_LINE', description: 'Height Adjustable Desk',     unit: 'EA',  default_rate: 2800, sort_order: 4 },
      { line_structure: 'SUB_HEADING',   description: 'Seating',                    unit: '',    default_rate: 0,    sort_order: 5 },
      { line_structure: 'STANDARD_LINE', description: 'Task Chair',                 unit: 'EA',  default_rate: 650,  sort_order: 6 },
      { line_structure: 'STANDARD_LINE', description: 'Visitor / Meeting Chair',    unit: 'EA',  default_rate: 450,  sort_order: 7 },
      { line_structure: 'SUB_HEADING',   description: 'Meeting & Collaboration',    unit: '',    default_rate: 0,    sort_order: 8 },
      { line_structure: 'STANDARD_LINE', description: 'Meeting Table',              unit: 'EA',  default_rate: 3500, sort_order: 9 },
      { line_structure: 'STANDARD_LINE', description: 'Collaborative / Lounge Seating', unit: 'EA', default_rate: 1200, sort_order: 10 },
      { line_structure: 'STANDARD_LINE', description: 'Furniture Installation',     unit: 'LS',  default_rate: 0,    sort_order: 11 },
    ],
  },
  {
    code: 'FF',
    name: "FF&E",
    order: 19,
    lines: [
      { line_structure: 'SUB_HEADING',   description: 'Kitchen Appliances',          unit: '',    default_rate: 0,    sort_order: 1 },
      { line_structure: 'STANDARD_LINE', description: 'Refrigerator',                unit: 'EA',  default_rate: 1800, sort_order: 2 },
      { line_structure: 'STANDARD_LINE', description: 'Dishwasher',                  unit: 'EA',  default_rate: 1200, sort_order: 3 },
      { line_structure: 'STANDARD_LINE', description: 'Microwave',                   unit: 'EA',  default_rate: 400,  sort_order: 4 },
      { line_structure: 'STANDARD_LINE', description: 'Coffee Machine',              unit: 'EA',  default_rate: 0,    sort_order: 5 },
      { line_structure: 'SUB_HEADING',   description: 'Fixtures & Fittings',         unit: '',    default_rate: 0,    sort_order: 6 },
      { line_structure: 'STANDARD_LINE', description: 'Toilet / Bathroom Accessories', unit: 'LS', default_rate: 2500, sort_order: 7 },
      { line_structure: 'STANDARD_LINE', description: 'Mirrors',                     unit: 'EA',  default_rate: 350,  sort_order: 8 },
      { line_structure: 'STANDARD_LINE', description: 'Artwork / Decorative Items',  unit: 'LS',  default_rate: 0,    sort_order: 9 },
      { line_structure: 'STANDARD_LINE', description: 'FF&E - Sundry Allowance',     unit: 'LS',  default_rate: 0,    sort_order: 10 },
    ],
  },
  {
    code: 'MW',
    name: 'Metal Work',
    order: 20,
    lines: [
      { line_structure: 'STANDARD_LINE', description: 'Structural Steel - Modifications', unit: 'LS', default_rate: 0, sort_order: 1 },
      { line_structure: 'STANDARD_LINE', description: 'Metal Balustrades',           unit: 'LM',  default_rate: 650,  sort_order: 2 },
      { line_structure: 'STANDARD_LINE', description: 'Steel Staircase',             unit: 'EA',  default_rate: 0,    sort_order: 3 },
      { line_structure: 'STANDARD_LINE', description: 'Perforated Metal Screens',    unit: 'M2',  default_rate: 450,  sort_order: 4 },
      { line_structure: 'STANDARD_LINE', description: 'Metal Framing / Feature',     unit: 'LS',  default_rate: 0,    sort_order: 5 },
      { line_structure: 'STANDARD_LINE', description: 'Misc Metal Work Allowance',   unit: 'LS',  default_rate: 0,    sort_order: 6 },
    ],
  },
  {
    code: 'SI',
    name: 'Signage',
    order: 21,
    lines: [
      { line_structure: 'STANDARD_LINE', description: 'Directional / Wayfinding Signage', unit: 'LS', default_rate: 0, sort_order: 1 },
      { line_structure: 'STANDARD_LINE', description: 'Room / Door Identification Signs', unit: 'EA', default_rate: 350, sort_order: 2 },
      { line_structure: 'STANDARD_LINE', description: 'Reception / Logo Signage',    unit: 'LS',  default_rate: 0,    sort_order: 3 },
      { line_structure: 'STANDARD_LINE', description: 'Compliance / Emergency Signage', unit: 'LS', default_rate: 1500, sort_order: 4 },
      { line_structure: 'STANDARD_LINE', description: 'Digital Signage / Display',   unit: 'EA',  default_rate: 0,    sort_order: 5 },
    ],
  },
  {
    code: 'WF',
    name: 'Window Furnishings',
    order: 22,
    lines: [
      { line_structure: 'STANDARD_LINE', description: 'Roller Blinds - Supply & Install', unit: 'M2', default_rate: 180, sort_order: 1 },
      { line_structure: 'STANDARD_LINE', description: 'Blockout Blinds',             unit: 'M2',  default_rate: 220,  sort_order: 2 },
      { line_structure: 'STANDARD_LINE', description: 'Vertical Blinds',             unit: 'M2',  default_rate: 150,  sort_order: 3 },
      { line_structure: 'STANDARD_LINE', description: 'Solar Film / Window Tinting', unit: 'M2',  default_rate: 95,   sort_order: 4 },
      { line_structure: 'STANDARD_LINE', description: 'Privacy Film / Decorative Film', unit: 'M2', default_rate: 120, sort_order: 5 },
    ],
  },
  {
    code: 'CE',
    name: 'Civil & External Works',
    order: 23,
    lines: [
      { line_structure: 'STANDARD_LINE', description: 'External Paving / Hardstand', unit: 'M2',  default_rate: 180,  sort_order: 1 },
      { line_structure: 'STANDARD_LINE', description: 'Car Park Line Marking',       unit: 'LS',  default_rate: 0,    sort_order: 2 },
      { line_structure: 'STANDARD_LINE', description: 'Landscaping',                 unit: 'LS',  default_rate: 0,    sort_order: 3 },
      { line_structure: 'STANDARD_LINE', description: 'Fencing / Gates',             unit: 'LS',  default_rate: 0,    sort_order: 4 },
      { line_structure: 'STANDARD_LINE', description: 'Drainage / Civil Works',      unit: 'LS',  default_rate: 0,    sort_order: 5 },
    ],
  },
  {
    code: 'ZZ',
    name: 'Miscellaneous & Contingency',
    order: 24,
    lines: [
      { line_structure: 'STANDARD_LINE', description: 'Contingency Allowance',       unit: 'LS',  default_rate: 0,    sort_order: 1 },
      { line_structure: 'STANDARD_LINE', description: 'Provisional Sum',             unit: 'LS',  default_rate: 0,    sort_order: 2 },
      { line_structure: 'STANDARD_LINE', description: 'PC Sum Items',                unit: 'LS',  default_rate: 0,    sort_order: 3 },
      { line_structure: 'STANDARD_LINE', description: 'Builders Margin Adjustment',  unit: 'LS',  default_rate: 0,    sort_order: 4 },
      { line_structure: 'STANDARD_LINE', description: 'Other / Sundry Allowance',    unit: 'LS',  default_rate: 0,    sort_order: 5 },
    ],
  },
];
