export const SAFETY_WALK_ITEMS = [
  { id: "sw01", question: "Site perimeter fencing and hoarding is secure and undamaged" },
  { id: "sw02", question: "Access and egress routes are clear and unobstructed" },
  { id: "sw03", question: "Site signage is legible, current, and in correct locations" },
  { id: "sw04", question: "Housekeeping — materials and waste are stored or removed appropriately" },
  { id: "sw05", question: "Plant and equipment has current plant registration / maintenance records visible" },
  { id: "sw06", question: "Workers are wearing appropriate PPE (hard hat, hi-vis, footwear, eye/ear protection)" },
  { id: "sw07", question: "Working at height controls are in place (scaffolding, edge protection, fall arrest)" },
  { id: "sw08", question: "Excavations and trenches are adequately shored, guarded, and signed" },
  { id: "sw09", question: "Crane / lifting operations are being conducted safely with exclusion zones maintained" },
  { id: "sw10", question: "Electrical installations and temporary power are protected and compliant" },
  { id: "sw11", question: "Hazardous chemicals are stored correctly with current SDS accessible" },
  { id: "sw12", question: "Fire extinguishers are present, in-date, and unobstructed" },
  { id: "sw13", question: "First aid kit is stocked and accessible" },
  { id: "sw14", question: "Site amenities (toilets, lunch room, wash stations) are clean and functional" },
  { id: "sw15", question: "Traffic management and vehicle/pedestrian separation is maintained" },
  { id: "sw16", question: "Hot works (welding, grinding) permits are current and conditions met" },
  { id: "sw17", question: "Confined space entry procedures are being followed where applicable" },
  { id: "sw18", question: "Subcontractors have their SWMS on site and workers have signed it" },
  { id: "sw19", question: "Induction records are current for all workers on site today" },
  { id: "sw20", question: "No evidence of alcohol or drug use observed" },
  { id: "sw21", question: "Environmental controls (sediment, noise, dust) are in place and functioning" },
  { id: "sw22", question: "Previous safety walk actions have been addressed and closed out" },
  {
    id: "sw23",
    question:
      "Psychosocial hazards observed — high workload, poor communication, worker isolation, aggression, or other psychosocial risks (VIC Psych Health Regs 2025)",
  },
] as const;
