// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Use the pooler for migrations because the direct host (db.*:5432) isn't reachable
  // from this environment.
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
