'use server';
import { prisma } from '@/lib/prisma';
import { requireAppUser } from '@/lib/auth';
import { revalidatePath } from 'next/cache';

export async function updateLineScope(lineScopeId: string, scopeText: string, estimateId: string) {
  const user = await requireAppUser();
  await prisma.estimateLineScope.update({
    where: { id: lineScopeId },
    data: { scopeText, isAutoGenerated: false, updatedById: user.id, updatedAt: new Date() },
  });
  revalidatePath(`/leads/${estimateId}/scope`);
}

export async function toggleLineInclusion(lineScopeId: string, include: boolean, estimateId: string) {
  await requireAppUser();
  await prisma.estimateLineScope.update({
    where: { id: lineScopeId },
    data: { includeInInvitation: include },
  });
  revalidatePath(`/leads/${estimateId}/scope`);
}

export async function regenerateScopeFromTemplate(
  lineScopeId: string,
  referenceItemId: string | null,
  estimateId: string
) {
  await requireAppUser();
  const estimate = await prisma.estimate.findFirst({ where: { id: estimateId }, select: { organisationId: true } });
  if (!estimate) return;

  const template = referenceItemId
    ? await prisma.scopeTemplate.findFirst({ where: { organisationId: estimate.organisationId, referenceItemId } })
    : null;

  if (template) {
    await prisma.estimateLineScope.update({
      where: { id: lineScopeId },
      data: { scopeText: template.scopeText, isAutoGenerated: true },
    });
  }
  revalidatePath(`/leads/${estimateId}/scope`);
}

export async function generateInvitation(
  estimateId: string,
  tradeSectionCode: string,
  invitationType: 'early_cost_advice' | 'tender',
  closeDate: string | null,
  notes: string | null
) {
  const user = await requireAppUser();

  // Get all included scope lines for this trade
  const scopeLines = await prisma.estimateLineScope.findMany({
    where: {
      includeInInvitation: true,
      estimateLine: { estimateId, tradeSection: { code: tradeSectionCode } },
    },
    include: {
      estimateLine: {
        include: {
          tradeSection: true,
          architectCode: { select: { code: true } },
        },
      },
    },
  });

  if (scopeLines.length === 0) return { error: 'No scope lines included for this trade.' };

  const estimate = await prisma.estimate.findFirst({
    where: { id: estimateId },
    select: { title: true, addressStreet: true, addressSuburb: true, addressState: true },
  });

  // Generate simple invitation text (PDF generation via external lib would be full implementation)
  const invitationText = buildInvitationText(
    estimate!,
    tradeSectionCode,
    invitationType,
    scopeLines,
    closeDate,
    notes
  );

  const invitation = await prisma.subcontractorInvitation.create({
    data: {
      estimateId,
      tradeSectionCode,
      invitationType,
      status: 'issued',
      issuedAt: new Date(),
      closeDate: closeDate ? new Date(closeDate) : null,
      notes,
      invitationPdfUrl: null,
      createdById: user.id,
    },
  });

  revalidatePath(`/leads/${estimateId}/scope`);
  return { invitationId: invitation.id };
}

function buildInvitationText(
  estimate: { title: string; addressStreet: string | null; addressSuburb: string | null; addressState: string | null },
  tradeCode: string,
  type: string,
  scopeLines: { scopeText: string; estimateLine: { description: string; quantity: unknown; unit: string | null; architectCode: { code: string } | null } }[],
  closeDate: string | null,
  notes: string | null
): string {
  const typeLabel = type === 'early_cost_advice' ? 'Early Cost Advice (ECA)' : 'Tender';
  return `AGERO GROUP PTY LTD — SUBCONTRACTOR INVITATION
Project: ${estimate.title}
Address: ${[estimate.addressStreet, estimate.addressSuburb, estimate.addressState].filter(Boolean).join(', ')}
Trade: ${tradeCode}
Type: ${typeLabel}
Close Date: ${closeDate ?? 'TBD'}

SCOPE OF WORKS
${scopeLines.map((l, i) => `${i + 1}. ${l.estimateLine.description}${l.estimateLine.architectCode ? ` [${l.estimateLine.architectCode.code}]` : ''} — ${Number(l.estimateLine.quantity).toFixed(2)} ${l.estimateLine.unit ?? ''}
   ${l.scopeText}`).join('\n\n')}

ITEMS WE MAY HAVE MISSED
[Subcontractor to complete]

ADDITIONAL INFORMATION REQUESTED
Please advise on buildability, alternative materials, programme impacts, or any items considered to have been omitted.

DISCLAIMER
Quantities shown are Agero's estimates only. Tenderers must satisfy themselves as to quantities and are invited to include any items they consider to have been omitted.

${notes ? `COVERING NOTES\n${notes}` : ''}`;
}
