import { prisma } from '@/lib/prisma';
import { requireAppUser } from '@/lib/auth';
import { notFound } from 'next/navigation';
import ScopeClient from './ScopeClient';

export default async function ScopePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const user = await requireAppUser();

  const estimate = await prisma.estimate.findFirst({
    where: { id, organisationId: user.organisationId },
    select: { id: true },
  });
  if (!estimate) notFound();

  const tradeSections = await prisma.estimateTradeSection.findMany({
    where: { estimateId: id },
    include: {
      lines: {
        where: { lineStructure: 'STANDARD_LINE' },
        include: { lineScope: true },
        orderBy: { order: 'asc' },
      },
    },
    orderBy: { order: 'asc' },
  });

  const invitations = await prisma.subcontractorInvitation.findMany({
    where: { estimateId: id },
    orderBy: { createdAt: 'desc' },
  });

  const serialise = tradeSections.map((ts) => ({
    id: ts.id,
    name: ts.name,
    code: ts.code,
    lines: ts.lines.map((l) => ({
      id: l.id,
      description: l.description,
      quantity: Number(l.quantity),
      unit: l.unit,
      lineScope: l.lineScope
        ? {
            id: l.lineScope.id,
            scopeText: l.lineScope.scopeText,
            isAutoGenerated: l.lineScope.isAutoGenerated,
            includeInInvitation: l.lineScope.includeInInvitation,
          }
        : null,
    })),
  }));

  return (
    <ScopeClient
      estimateId={id}
      tradeSections={serialise}
      invitations={invitations.map((inv) => ({
        id: inv.id,
        tradeSectionCode: inv.tradeSectionCode,
        invitationType: inv.invitationType,
        status: inv.status,
        issuedAt: inv.issuedAt?.toISOString() ?? null,
        closeDate: inv.closeDate?.toISOString() ?? null,
      }))}
    />
  );
}
