'use client';
import { useState, useTransition } from 'react';
import { updateLineScope, toggleLineInclusion, generateInvitation } from './actions';

type LineScope = { id: string; scopeText: string; isAutoGenerated: boolean; includeInInvitation: boolean };
type Line = { id: string; description: string; quantity: number; unit: string | null; lineScope: LineScope | null };
type TradeSection = { id: string; name: string; code: string | null; lines: Line[] };
type Invitation = { id: string; tradeSectionCode: string; invitationType: string; status: string; issuedAt: string | null; closeDate: string | null };

export default function ScopeClient({
  estimateId,
  tradeSections,
  invitations,
}: {
  estimateId: string;
  tradeSections: TradeSection[];
  invitations: Invitation[];
}) {
  const [editingScope, setEditingScope] = useState<Record<string, string>>({});
  const [showInviteModal, setShowInviteModal] = useState(false);
  const [inviteType, setInviteType] = useState<'early_cost_advice' | 'tender'>('early_cost_advice');
  const [inviteTrade, setInviteTrade] = useState('');
  const [inviteCloseDate, setInviteCloseDate] = useState('');
  const [inviteNotes, setInviteNotes] = useState('');
  const [isPending, startTransition] = useTransition();

  const linesWithNoScope = tradeSections.flatMap((ts) => ts.lines.filter((l) => !l.lineScope));
  const totalIncluded = tradeSections.flatMap((ts) =>
    ts.lines.filter((l) => l.lineScope?.includeInInvitation)
  ).length;

  function handleScopeEdit(lineScopeId: string, newText: string) {
    setEditingScope((prev) => ({ ...prev, [lineScopeId]: newText }));
  }

  function handleScopeBlur(lineScopeId: string, originalText: string) {
    const newText = editingScope[lineScopeId];
    if (newText !== undefined && newText !== originalText) {
      startTransition(() => updateLineScope(lineScopeId, newText, estimateId));
    }
  }

  function handleGenerate() {
    startTransition(async () => {
      await generateInvitation(estimateId, inviteTrade, inviteType, inviteCloseDate || null, inviteNotes || null);
      setShowInviteModal(false);
    });
  }

  if (tradeSections.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center h-full gap-3">
        <p className="text-sm text-zinc-500">No cost plan lines yet. Import a takeoff or add lines to the cost plan first.</p>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between px-6 py-4 border-b border-zinc-200 bg-white shrink-0">
        <div>
          <h2 className="text-lg font-semibold text-zinc-900">Scope of Works</h2>
          <p className="text-xs text-zinc-500 mt-0.5">{totalIncluded} lines included in invitation</p>
        </div>
        <button
          onClick={() => { setInviteTrade(tradeSections[0]?.code ?? ''); setShowInviteModal(true); }}
          className="px-4 py-2 bg-blue-600 text-white text-sm font-medium rounded-md hover:bg-blue-700"
        >
          Generate Invitation Package
        </button>
      </div>

      <div className="flex-1 overflow-auto p-6 space-y-8">
        {/* Trade sections */}
        {tradeSections.map((ts) => (
          <div key={ts.id}>
            <div className="flex items-center justify-between mb-3">
              <h3 className="text-sm font-semibold text-zinc-900 uppercase tracking-wider">
                {ts.name}
              </h3>
              <div className="flex gap-2">
                <button
                  onClick={() => {
                    const lineScopes = ts.lines.filter((l) => l.lineScope).map((l) => l.lineScope!);
                    for (const ls of lineScopes) {
                      startTransition(() => toggleLineInclusion(ls.id, true, estimateId));
                    }
                  }}
                  className="text-xs text-blue-600 hover:underline"
                >
                  Include all
                </button>
                <span className="text-zinc-300">|</span>
                <button
                  onClick={() => {
                    const lineScopes = ts.lines.filter((l) => l.lineScope).map((l) => l.lineScope!);
                    for (const ls of lineScopes) {
                      startTransition(() => toggleLineInclusion(ls.id, false, estimateId));
                    }
                  }}
                  className="text-xs text-zinc-500 hover:underline"
                >
                  Exclude all
                </button>
              </div>
            </div>

            <div className="bg-white rounded-lg border border-zinc-200 overflow-hidden">
              {ts.lines.length === 0 ? (
                <p className="px-4 py-3 text-sm text-zinc-400">No standard lines in this trade section.</p>
              ) : (
                ts.lines.map((line, idx) => (
                  <div
                    key={line.id}
                    className={`${idx < ts.lines.length - 1 ? 'border-b border-zinc-100' : ''} p-4 flex gap-4`}
                  >
                    {/* Include toggle */}
                    <div className="shrink-0 pt-0.5">
                      {line.lineScope && (
                        <input
                          type="checkbox"
                          checked={line.lineScope.includeInInvitation}
                          onChange={(e) =>
                            startTransition(() =>
                              toggleLineInclusion(line.lineScope!.id, e.target.checked, estimateId)
                            )
                          }
                          className="w-4 h-4 rounded border-zinc-300"
                        />
                      )}
                    </div>

                    {/* Content */}
                    <div className="flex-1 min-w-0">
                      <div className="flex items-baseline gap-2 mb-2">
                        <span className="text-sm font-medium text-zinc-900">{line.description}</span>
                        <span className="text-xs text-zinc-400">{line.quantity.toFixed(2)} {line.unit}</span>
                      </div>

                      {line.lineScope ? (
                        <textarea
                          value={editingScope[line.lineScope.id] ?? line.lineScope.scopeText}
                          onChange={(e) => handleScopeEdit(line.lineScope!.id, e.target.value)}
                          onBlur={() => handleScopeBlur(line.lineScope!.id, line.lineScope!.scopeText)}
                          rows={2}
                          className={`w-full px-3 py-2 text-sm border border-zinc-200 rounded-md resize-none focus:outline-none focus:ring-2 focus:ring-blue-500 transition-colors ${
                            line.lineScope.isAutoGenerated && !(editingScope[line.lineScope.id] !== undefined)
                              ? 'text-zinc-400 italic'
                              : 'text-zinc-800'
                          }`}
                        />
                      ) : (
                        <div className="px-3 py-2 text-sm text-zinc-400 border border-dashed border-zinc-200 rounded-md">
                          No scope text. Add lines via takeoff import or manually edit the cost plan.
                        </div>
                      )}
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        ))}

        {/* Issued invitations */}
        {invitations.length > 0 && (
          <div>
            <h3 className="text-sm font-semibold text-zinc-900 mb-3">Issued Invitations</h3>
            <div className="bg-white rounded-lg border border-zinc-200 overflow-hidden">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-zinc-100 bg-zinc-50">
                    <th className="text-left px-4 py-2.5 font-medium text-zinc-500 text-xs">Trade</th>
                    <th className="text-left px-4 py-2.5 font-medium text-zinc-500 text-xs">Type</th>
                    <th className="text-left px-4 py-2.5 font-medium text-zinc-500 text-xs">Status</th>
                    <th className="text-left px-4 py-2.5 font-medium text-zinc-500 text-xs">Issued</th>
                    <th className="text-left px-4 py-2.5 font-medium text-zinc-500 text-xs">Close Date</th>
                  </tr>
                </thead>
                <tbody>
                  {invitations.map((inv, idx) => (
                    <tr key={inv.id} className={idx < invitations.length - 1 ? 'border-b border-zinc-100' : ''}>
                      <td className="px-4 py-2.5 font-mono text-xs text-zinc-700">{inv.tradeSectionCode}</td>
                      <td className="px-4 py-2.5 text-xs text-zinc-600">
                        {inv.invitationType === 'early_cost_advice' ? 'ECA' : 'Tender'}
                      </td>
                      <td className="px-4 py-2.5">
                        <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${
                          inv.status === 'issued' ? 'bg-green-100 text-green-700' :
                          inv.status === 'closed' ? 'bg-zinc-100 text-zinc-500' : 'bg-amber-100 text-amber-700'
                        }`}>
                          {inv.status.charAt(0).toUpperCase() + inv.status.slice(1)}
                        </span>
                      </td>
                      <td className="px-4 py-2.5 text-xs text-zinc-500">
                        {inv.issuedAt ? new Date(inv.issuedAt).toLocaleDateString('en-AU') : '—'}
                      </td>
                      <td className="px-4 py-2.5 text-xs text-zinc-500">
                        {inv.closeDate ? new Date(inv.closeDate).toLocaleDateString('en-AU') : '—'}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </div>

      {/* Generate invitation modal */}
      {showInviteModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-md">
            <div className="flex items-center justify-between px-6 py-4 border-b border-zinc-200">
              <h2 className="text-base font-semibold text-zinc-900">Generate Invitation Package</h2>
              <button onClick={() => setShowInviteModal(false)} className="text-zinc-400 hover:text-zinc-700">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            <div className="px-6 py-5 space-y-4">
              <div>
                <label className="block text-xs font-medium text-zinc-700 mb-1">Trade Section</label>
                <select
                  value={inviteTrade}
                  onChange={(e) => setInviteTrade(e.target.value)}
                  className="w-full px-3 py-2 text-sm border border-zinc-200 rounded-md"
                >
                  {tradeSections.map((ts) => (
                    <option key={ts.id} value={ts.code ?? ''}>{ts.name}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-xs font-medium text-zinc-700 mb-1">Invitation Type</label>
                <div className="flex gap-3">
                  <label className="flex items-center gap-2 text-sm cursor-pointer">
                    <input type="radio" value="early_cost_advice" checked={inviteType === 'early_cost_advice'} onChange={() => setInviteType('early_cost_advice')} />
                    Early Cost Advice (ECA)
                  </label>
                  <label className="flex items-center gap-2 text-sm cursor-pointer">
                    <input type="radio" value="tender" checked={inviteType === 'tender'} onChange={() => setInviteType('tender')} />
                    Tender
                  </label>
                </div>
              </div>
              <div>
                <label className="block text-xs font-medium text-zinc-700 mb-1">Close Date</label>
                <input
                  type="date"
                  value={inviteCloseDate}
                  onChange={(e) => setInviteCloseDate(e.target.value)}
                  className="w-full px-3 py-2 text-sm border border-zinc-200 rounded-md"
                />
              </div>
              <div>
                <label className="block text-xs font-medium text-zinc-700 mb-1">Covering Instructions</label>
                <textarea
                  value={inviteNotes}
                  onChange={(e) => setInviteNotes(e.target.value)}
                  rows={3}
                  placeholder="Additional instructions to subcontractors..."
                  className="w-full px-3 py-2 text-sm border border-zinc-200 rounded-md resize-none"
                />
              </div>
              <div className="pt-2 flex gap-3">
                <button
                  onClick={handleGenerate}
                  disabled={isPending || !inviteTrade}
                  className="flex-1 px-4 py-2 bg-blue-600 text-white text-sm font-medium rounded-md hover:bg-blue-700 disabled:opacity-50"
                >
                  {isPending ? 'Generating...' : 'Generate & Issue'}
                </button>
                <button onClick={() => setShowInviteModal(false)} className="px-4 py-2 text-sm border border-zinc-200 rounded-md">
                  Cancel
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
