// eslint-disable-next-line @typescript-eslint/no-explicit-any
type DocDef = Record<string, any>;

const GREY = "#f4f4f5";
const DARK = "#18181b";

export interface AuditEvidenceRecord {
  form: string;
  date: string;
  signatory?: string;
  detail?: string;
  pdfUrl?: string | null;
}

export interface AuditEvidenceSection {
  clause: string;
  requirement: string;
  records: AuditEvidenceRecord[];
}

export interface AuditEvidencePdfData {
  orgName: string;
  fromLabel: string;
  toLabel: string;
  generatedBy: string;
  sections: AuditEvidenceSection[];
  consultationEvents: { type: string; date: string; detail: string }[];
}

export async function generateAuditEvidencePdf(data: AuditEvidencePdfData): Promise<Buffer> {
  const { default: PdfPrinter } = await import("pdfmake");
  const fonts = {
    Helvetica: {
      normal: "Helvetica",
      bold: "Helvetica-Bold",
      italics: "Helvetica-Oblique",
      bolditalics: "Helvetica-BoldOblique",
    },
  };
  const printer = new PdfPrinter(fonts);
  const cell = (text: string, opts: DocDef = {}) => ({ text, fontSize: 8, margin: [5, 3, 5, 3], ...opts });
  const head = (text: string) => ({ text, bold: true, fontSize: 8, fillColor: GREY, color: "#71717a", margin: [5, 3, 5, 3] });

  const content: DocDef[] = [
    { text: "ISO 45001 AUDIT EVIDENCE PACKAGE", style: "header" },
    { text: data.orgName, style: "subheader", margin: [0, 4, 0, 0] },
    { text: `Period: ${data.fromLabel} – ${data.toLabel}`, fontSize: 9, color: "#71717a", margin: [0, 2, 0, 0] },
    { text: `Generated by ${data.generatedBy} on ${new Date().toLocaleDateString("en-AU")}`, fontSize: 8, color: "#a1a1aa", margin: [0, 2, 0, 0] },
  ];

  for (const s of data.sections) {
    content.push({
      text: `Clause ${s.clause} — ${s.requirement}`,
      style: "sectionHeader",
      margin: [0, 18, 0, 6],
    });
    if (s.records.length === 0) {
      content.push({ text: "No records in this period.", fontSize: 8, italics: true, color: "#a1a1aa" });
      continue;
    }
    content.push({
      table: {
        headerRows: 1,
        widths: ["*", 60, 90, "*"],
        body: [
          [head("Form / Evidence"), head("Date"), head("Signatory"), head("Detail")],
          ...s.records.map((r) => [
            cell(r.form),
            cell(r.date),
            cell(r.signatory ?? "—"),
            cell(r.detail ?? "—"),
          ]),
        ],
      },
      layout: "lightHorizontalLines",
    });
  }

  content.push({ text: "Consultation events", style: "sectionHeader", margin: [0, 18, 0, 6] });
  if (data.consultationEvents.length === 0) {
    content.push({ text: "No consultation events in this period.", fontSize: 8, italics: true, color: "#a1a1aa" });
  } else {
    content.push({
      table: {
        headerRows: 1,
        widths: [120, 60, "*"],
        body: [
          [head("Type"), head("Date"), head("Detail")],
          ...data.consultationEvents.map((e) => [cell(e.type), cell(e.date), cell(e.detail)]),
        ],
      },
      layout: "lightHorizontalLines",
    });
  }

  const dd: DocDef = {
    defaultStyle: { font: "Helvetica", fontSize: 9, color: DARK },
    pageMargins: [36, 46, 36, 46],
    footer: (currentPage: number, pageCount: number) => ({
      margin: [36, 0, 36, 0],
      columns: [
        { text: `${data.orgName} · ISO 45001 audit evidence`, fontSize: 7, color: "#a1a1aa" },
        { text: `Page ${currentPage} of ${pageCount}`, fontSize: 7, color: "#a1a1aa", alignment: "right" },
      ],
    }),
    content,
    styles: {
      header: { fontSize: 16, bold: true, color: DARK },
      subheader: { fontSize: 11, color: "#71717a" },
      sectionHeader: { fontSize: 12, bold: true, color: DARK },
    },
  };

  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const doc = printer.createPdfKitDocument(dd);
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
    doc.end();
  });
}
