export const TRADE_CATEGORIES = [
  "Demolition",
  "Carpentry/Partitions",
  "Ceiling Works",
  "Construction General",
  "Doors",
  "Glass",
  "Painting",
  "Floor Preparation",
  "Carpet/Vinyl",
  "Concrete Floor Finishes",
  "Floor Sanding",
  "Timber",
  "Tiling",
  "Joinery",
  "Furniture",
  "FFE",
  "Signage",
  "Blinds",
  "Cleaning",
  "Electrical",
  "Mechanical",
  "Plumbing",
  "Fire",
  "Security",
  "Structural Engineering",
  "Services Engineering",
  "Building Surveyor",
  "Interior Design/Architecture",
  "Landscaping",
  "Scaffolding",
  "Waterproofing",
  "Roofing",
] as const;

export type TradeCategory = (typeof TRADE_CATEGORIES)[number];
